# ------------------------------------------------------------
# -----------------     Phil data configs    -----------------
# ------------------------------------------------------------

new_base_data: &new_base_data
  transcript_save_dir: "/data1/morrisq/ian/rna_contrast/transcripts"
  n_tracks: 6
  proportion_to_mask: 0.15
  utr_dropping: False
  weighted_split: False
  weight: 0.5 # same as orthology_weight (which was here before) - larger weight means more orthologs
  cds_only: False
  drop_track_probability_6: 0.0
  drop_track_probability_5: 0.0
  combine_probability: 0.0
  mask_track_probability_5: 0.15
  mask_track_probability_6: 0.15
  mask_value: 0.0
  no_splice_isoforms: False
  no_ortho_isoforms: False


high_mask_splice_only: &high_mask_splice_only
  transcript_save_dir: "/data1/morrisq/ian/rna_contrast/transcripts"
  n_tracks: 6
  proportion_to_mask: 0.30
  utr_dropping: False
  weighted_split: True
  weight: 0.0 # same as orthology_weight (which was here before) - larger weight means more orthologs
  cds_only: False
  drop_track_probability_6: 0.0
  drop_track_probability_5: 0.0
  combine_probability: 0.0
  mask_track_probability_5: 0.30
  mask_track_probability_6: 0.30
  mask_value: 0.0
  no_splice_isoforms: False
  no_ortho_isoforms: False

new_splice_to_toga_combined_15_mask:
  <<: *new_base_data
  short_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_shorter.pkl"
  long_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_longer.pkl"
  proportion_to_mask: 0.15
  combine_probability: 1.0
  mask_track_probability_5: 0.3
  mask_track_probability_6: 0.3

new_splice_to_toga_combined_30_mask:
  <<: *new_base_data
  short_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_shorter.pkl"
  long_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_longer.pkl"
  proportion_to_mask: 0.30
  combine_probability: 1.0
  mask_track_probability_5: 0.3
  mask_track_probability_6: 0.3

new_splice_to_toga_combined_no_mask:
  <<: *new_base_data
  short_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_shorter.pkl"
  long_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_longer.pkl"
  proportion_to_mask: 0.0
  combine_probability: 1.0
  mask_track_probability_5: 0.0
  mask_track_probability_6: 0.0

new_splice_to_toga_combined_no_splice:
  <<: *new_base_data
  short_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_shorter.pkl"
  long_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_longer.pkl"
  proportion_to_mask: 0.30
  combine_probability: 1.0
  mask_track_probability_5: 0.3
  mask_track_probability_6: 0.3
  no_splice_isoforms: True

new_splice_to_toga_combined_no_splice_no_ortho:
  <<: *new_base_data
  short_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_shorter.pkl"
  long_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_longer.pkl"
  proportion_to_mask: 0.30
  mask_track_probability_5: 0.3
  mask_track_probability_6: 0.3
  no_splice_isoforms: True
  no_ortho_isoforms: True

new_splice_to_toga_combined_no_splice_no_ortho_no_mask:
  <<: *new_base_data
  short_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_shorter.pkl"
  long_transcript_map_path: "/data1/morrisq/ian/rna_contrast/maps/COMB-eutheria-splice_all_basic_s-st_longer.pkl"
  proportion_to_mask: 0.0
  mask_track_probability_5: 0.0
  mask_track_probability_6: 0.0
  no_splice_isoforms: True
  no_ortho_isoforms: True

