resnet_base: &resnet_base
  model_class: "resnet"
  num_classes: 1
  pooling_layer: "max_pool"
  add_shift: True
  increase_dialtion: False
  resnet: "dilated_small"
  norm_type: "batchnorm"
  kernel_size: 2
  global_pooling_layer: "avgpool"

mamba_base: &mamba_base
  model_class: "ssm"
  ssm_model_dim: 256
  ssm_n_layers: 3
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False
  bidirectional:
  bidirectional_strategy: "add"
  bidirectional_weight_tie: True
  gradient_checkpointing: False

mamba_base_4t: &mamba_base_4t
  model_class: "ssm"
  ssm_model_dim: 512
  ssm_n_layers: 3
  n_tracks: 4
  predict_splice_codon: False
  predict_masked: False
  bidirectional:
  bidirectional_strategy: "add"
  bidirectional_weight_tie: True
  gradient_checkpointing: False

mamba_large: &mamba_large
  model_class: "ssm"
  ssm_model_dim: 512
  ssm_n_layers: 4
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False
  bidirectional:
  bidirectional_strategy: "add"
  bidirectional_weight_tie: True
  gradient_checkpointing: False

mamba_large_4t: &mamba_large_4t
  model_class: "ssm"
  ssm_model_dim: 512
  ssm_n_layers: 4
  n_tracks: 4
  predict_splice_codon: False
  predict_masked: False
  bidirectional:
  bidirectional_strategy: "add"
  bidirectional_weight_tie: True
  gradient_checkpointing: False

mamba_deep_4t: &mamba_deep_4t
  model_class: "ssm"
  ssm_model_dim: 512
  ssm_n_layers: 6
  n_tracks: 4
  predict_splice_codon: False
  predict_masked: False
  bidirectional:
  bidirectional_strategy: "add"
  bidirectional_weight_tie: True
  gradient_checkpointing: False

mamba_deep: &mamba_deep
  model_class: "ssm"
  ssm_model_dim: 512
  ssm_n_layers: 6
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False
  bidirectional:
  bidirectional_strategy: "add"
  bidirectional_weight_tie: True
  gradient_checkpointing: False

dilated_resnet_small: &dilated_resnet_small
  model_class: "resnet"
  resnet: "dilated_small"
  num_classes: 1
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False

dilated_resnet_medium: &dilated_resnet_medium
  model_class: "resnet"
  resnet: "dilated_medium"
  num_classes: 1
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False

saluki_small: &saluki_small
  model_class: "saluki"
  saluki: "saluki_small"
  num_classes: 1
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False

saluki_medium: &saluki_medium
  model_class: "saluki"
  saluki: "saluki_medium"
  num_classes: 1
  n_tracks: 6
  predict_splice_codon: False
  predict_masked: False