default: &default_optim
  model_lr: 0.0005
  model_weight_decay: 0.00001
  projection_head_lr: 0.001
  projection_head_weight_decay: 0.0001
  max_weight_decay: -1
  loss_fn: 'dcl'
  clipnorm: 5

published: &published
  model_lr: 0.001
  model_weight_decay: 0.00005
  projection_head_lr: 0.001
  projection_head_weight_decay: 0.0001
  max_weight_decay: -1
  loss_fn: 'dcl'
  clipnorm: 5

underweight_ortho_self:
  <<: *published
  ortho_weight: 0.2
  self_weight: 0.2

underweight_ortho_self_0.5:
  <<: *published
  ortho_weight: 0.5
  self_weight: 0.5

underweight_ortho_self_0.8:
  <<: *published
  ortho_weight: 0.8
  self_weight: 0.8

underweight_ortho_0.8:
  <<: *published
  ortho_weight: 0.8

underweight_ortho_0.7:
  <<: *published
  ortho_weight: 0.7


dual_heads:
  <<: *published
  use_dual_heads: True

lower_lr:
  <<: *published
  model_lr: 0.0001

anneal:
  model_lr: 0.0005
  model_weight_decay: 0.00001
  projection_head_lr: 0.001
  projection_head_weight_decay: 0.0001
  max_weight_decay: 0.0001
  loss_fn: 'dcl'
  clipnorm: 5

grid:
  model_lr: 0.001
  model_weight_decay: 0.00001
  projection_head_lr: 0.001
  projection_head_weight_decay: 0.0001
  max_weight_decay: 0.0001
  loss_fn: 'dcl'
  clipnorm: 5

high_wd:
  model_lr: 0.0005
  model_weight_decay: 0.00001
  projection_head_lr: 0.001
  projection_head_weight_decay: 0.0001
  max_weight_decay: 0.001
  loss_fn: 'dcl'
  clipnorm: 5

published_mlm_only:
  model_lr: 0.001
  model_weight_decay: 0.00005
  projection_head_lr: 0.001
  projection_head_weight_decay: 0.0001
  max_weight_decay: -1
  loss_fn: 'mlm'
  clipnorm: 5
