default: &default
  projection_body: 512
  projection_head_size: 128
  projection_norm_type: batchnorm
  projection_head_num: 4

default_256:
  <<: *default
  representation_dim: 256

default_512:
  <<: *default
  representation_dim: 512

default_1024:
  <<: *default
  representation_dim: 1024

grid:
  projection_body: 512
  projection_head_size: 128
  projection_norm_type: batchnorm
  representation_dim: 256

default_dino:
  <<: *default
  representation_dim: 512
  projection_body:: 1024
  projection_head_size: 2048
  projection_bottleneck: 256
  projection_norm_type: ""
  projection_n_layers: 3
  projection_norm_last_layer: True