default: &default
  rand_seed: 0
  number_steps: 20000
  mixed_precision: True
  wandb_run_dir: "/home/dalalt1/compute/Orthrus/runs"
  split_by_length: True
  mlm_end_weight:
  mlm_anneal_steps:
  mlm_start_weight:
  mask_prop: 0.0
  logging: True
  reconstruct_unmasked_prop: 0.0

ablation: &ablation
  rand_seed: 0
  number_steps: 20000
  mixed_precision: True
  wandb_run_dir: "/data1/morrisq/fradkinp/ablation_runs"
  split_by_length: True
  mlm_end_weight:
  mlm_anneal_steps:
  mlm_start_weight:
  mask_prop: 0.0
  logging: True
  reconstruct_unmasked_prop: 0.0


a40_ssm_256_3:
  <<: *default
  gpu_batch_sizes: [40, 240, 40]

a100_ssm_256_3:
  <<: *default
  gpu_batch_sizes: [150, 500, 150]

a100_ssm_512_4:
  <<: *default
  gpu_batch_sizes: [65, 210, 65]
  mask_prop: 0.0

a100_ssm_512_4_half:
  <<: *default
  gpu_batch_sizes: [30, 100, 30]

a100_ssm_512_4_quarter:
  <<: *default
  gpu_batch_sizes: [15, 50, 15]

a100_ssm_512_6_huge:
  <<: *default
  number_steps: 20000
  gpu_batch_sizes: [25, 75, 25]
  mask_prop: 0.0

a100_ssm_512_18:
  <<: *default
  number_steps: 40000
  gpu_batch_sizes: [16, 50, 16]
  mask_prop: 0.0

a100_ssm_512_18_mlm_only:
  <<: *default
  number_steps: 40000
  number_epochs: 35
  gpu_batch_sizes: [10, 40, 10]
  mask_prop: 0.15

a100_ssm_512_6_huge_18_mlm:
  <<: *default
  number_steps: 23600
  gpu_batch_sizes: [18, 54, 18]
  mask_prop: 0.15
  mlm_end_weight: 2.0
  mlm_anneal_steps: 5000
  mlm_start_weight: 1.0
  cl_start_weight: 1.5
  cl_anneal_steps: 5000
  cl_end_weight: 1.0

a100_ssm_512_6_huge_mlm:
  <<: *default
  number_steps: 20000 #22132
  gpu_batch_sizes: [25, 75, 25] #[22, 65, 22]
  mask_prop: 0.15
  mlm_end_weight: 2.0
  mlm_anneal_steps: 5000
  mlm_start_weight: 1.0

a100_ssm_512_6:
  <<: *default
  rand_seed: 0
  gpu_batch_sizes: [50, 150, 50]
  mask_prop: 0.0
  number_steps: 20000

a100_ssm_512_6_mlm_only_randseed0:
  <<: *default
  rand_seed: 0
  gpu_batch_sizes: [45, 130, 45]
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 1.7
  mlm_end_weight: 1.7

a100_ssm_512_4_long:
  <<: *default
  number_steps: 30000
  gpu_batch_sizes: [65, 210, 65]

a100_ssm_512_4_mlm:
  <<: *default
  gpu_batch_sizes: [55, 170, 55]
  mask_prop: 0.15
  mlm_end_weight: 2.0
  mlm_anneal_steps: 5000
  mlm_start_weight: 1.0

a100_ssm_512_6_deep_mlm_05_95:
  <<: *default
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.95
  mlm_end_weight: 0.95
  cl_anneal_steps: 20000
  cl_start_weight: 0.05
  cl_end_weight: 0.05

a100_ssm_512_6_deep_mlm_50_50:
  <<: *default
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.5
  mlm_end_weight: 0.5
  cl_anneal_steps: 20000
  cl_start_weight: 0.5
  cl_end_weight: 0.5

a100_ssm_512_6_deep_mlm_95_05:
  <<: *default
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.05
  mlm_end_weight: 0.05
  cl_anneal_steps: 20000
  cl_start_weight: 0.95
  cl_end_weight: 0.95

a100_ssm_512_80_mlm:
  <<: *default
  gpu_batch_sizes: [18, 54, 18]
  mask_prop: 0.15
  number_steps: 28400
  mlm_anneal_steps: 14200
  mlm_start_weight: 0.0
  mlm_end_weight: 3.0
  cl_anneal_steps: 28400
  cl_start_weight: 1.0
  cl_end_weight: 1.0

a100_ssm_1024_12_mlm_checkpointing:
  <<: *default
  gpu_batch_sizes: [18, 54, 18]
  mask_prop: 0.15
  number_steps: 30000
  mlm_anneal_steps: 30000
  mlm_start_weight: 0.95
  mlm_end_weight: 0.95
  cl_anneal_steps: 30000
  cl_start_weight: 0.05
  cl_end_weight: 0.05

a40_grid:
  rand_seed: 0
  number_steps: 20000
  mixed_precision: True
  wandb_run_dir: "/home/dalalt1/compute/Orthrus/runs"
  split_by_length: True
  gpu_batch_sizes: [40, 240, 40]
  mask_prop: 0.0


a100_ssm_512_6_deep_mlm_05_95_ablation:
  <<: *ablation
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.95
  mlm_end_weight: 0.95
  cl_anneal_steps: 20000
  cl_start_weight: 0.05
  cl_end_weight: 0.05

a100_ssm_512_6_deep_only_cl_ablation:
  <<: *ablation
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.0
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.0
  mlm_end_weight: 0.0
  cl_anneal_steps: 20000
  cl_start_weight: 1.0
  cl_end_weight: 1.0

a100_ssm_512_6_deep_only_mlm_ablation:
  <<: *ablation
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 1.0
  mlm_end_weight: 1.0
  cl_anneal_steps: 20000
  cl_start_weight: 0.0
  cl_end_weight: 0.0


a100_cnn_512_6_deep_cl:
  <<: *ablation
  gpu_batch_sizes: [20, 80, 20]
  rand_seed: 0
  mask_prop: 0.0
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.0
  mlm_end_weight: 0.0
  cl_anneal_steps: 20000
  cl_start_weight: 1.0
  cl_end_weight: 1.0

a100_ssm_512_6_deep_mlm_05_95_ablation_unmasked_05:
  <<: *ablation
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 0.95
  mlm_end_weight: 0.95
  cl_anneal_steps: 20000
  cl_start_weight: 0.05
  cl_end_weight: 0.05
  reconstruct_unmasked_prop: 0.05

a100_ssm_512_6_deep_only_mlm_unmasked_05:
  <<: *ablation
  gpu_batch_sizes: [30, 130, 30]
  rand_seed: 0
  mask_prop: 0.15
  number_steps: 20000
  mlm_anneal_steps: 20000
  mlm_start_weight: 1.7
  mlm_end_weight: 1.7
  cl_anneal_steps: 20000
  cl_start_weight: 0.0
  cl_end_weight: 0.0
  reconstruct_unmasked_prop: 0.05
